# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Login |
  jobs:
    - job: Login
      steps:
      - script: |
          az login -u $(AZURE_USERNAME) -p $(AZURE_PASSWORD)
      - script: |
          echo "Login Successfull"
    - job: KeyVaultAccess
      steps:
      - script: |
          echo "getting data from key vault"
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        echo My Step1
    - script: |
        echo My Step2 $(STAGE)
- stage: Calibrate
  jobs:
  - job: Run
    steps:
    - script: |
        echo So Many Stages
        echo Testing Matters
        
    